[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rensis"
version = "1.0.5"
dependencies = [
  "nsisunbz2",
  "pefile",
  "yara-python"
]
requires-python = ">=3.11"

[tool.setuptools.package-data]
"rensis.data" = ["*.yar"]
